Public Class AddressStdRequest {
   
   /* public String firmName ; 
    public String city;
    public String postalCode; 
    public String stateProvince;
    public String[] streets;

   Public AddressStdRequest (String firmName, String city, String postalCode, String stateProvince, String[] streets ){
       firmName = firmName ;
       city= city;
       postalCode = postalCode;
       stateProvince =  stateProvince;
       streets = streets;
   }*/
   
   /* 28/11/2012*/
   public String firmName ; 
   public String city;
   public String postalCode; 
   public String stateProvince;
   public String streets;
 

}